### PR TITLE
Update to latest Dolphin version

### PR DESCRIPTION
**Pull request by TomBebb**

### CODE REVIEW

**Comment by inactive123** [comment]
Hi there, can this be rebased, and was this rebase properly tested and did everything work that used to work?

**Comment by i30817** [comment]
Does this pr finally enable vulkan for the core? Or am i hallucinating it never worked in the RA core?

**Comment by cyberluke** [comment]
Vulkan with Dolphin and RA does not work for me on current RA. I was about to post a bug here. Why we need to wait 2 years for some pull request? Is anybody alive here or is this project dead?

**Comment by jvalecillos** [comment]
Is there a particular reason why the fork is not kept in sync with [upstream](https://github.com/dolphin-emu/dolphin) (dolphin-emu/dolphin)?

I imagine **it is a challenge now because there are 3K more commits in upstream**, but _if the fork is rebased on a regular basis it would be easier to track the changes_.

Keeping it out of sync for 2 years doesn't seem like a good idea, but again I'm missing the context.

**Comment by i30817** [comment]
Probably because many RA cores don't actually have regular maintainers. Especially complex ones that want to do their own thing (like this one with multi-threading, vulkan context etc).

They have 'porters'. Keeping a core uptodate is only simple if the core isn't changing that much, in cases where both the core and upstream change a lot, the drift becomes unfeasible until a new 'port' happens a few years down the line because the modifications done for issues that no longer have any relevance upstream or never did, can no longer be usefully grafted onto upstream.

It'd not like dolphin core is the only one this happens to. Too few people maintaining cores, too many porters scratching a itch and then dropping the core like a heavy lead object for 'the team' to modify (the team that i imagine has little intention of spending dozens of hours per year fixing merge conflicts).

**Comment by inactive123** [comment]
Unless you have something meaningful to add to our development process, keep misguided opinions on our development cycle to yourself. If there are going to be repeat offenses of this where users will get misinformed about Libretro developers/maintainers, moderation will be put into place in this organization. We don't need armchair referees on our Github.

As for this core, it needs to become a hard fork. Nobody is helped by a shallow upstream that can't live up to its full potential. Personally there is also zero motivation to chase after upstream commits, especially when this emulator is more or less 'finished' and in maintenance mode, and the team is actively unnecessarily hostile and non conducive to any kind of working relationship. We are better off making a complete hard fork that plays to Libretro's strengths better. A lot of the architectural decisions in this emulator are not only bloaty, they actively get in the way of a proper Libretro implementation catering to the kinds of things we care about.

We are getting tired of 3rd parties in here wrongly assuming our development reasons and then misinforming our userbase with their takes on things. These happen to usually be people who have nothing to add to our development process either, have never made a single commit, will never make a PR in their lives, and are the first to go out there joining some crusade against us whenever some outsiders love to dogpile on us again. Time to start putting the brakes on this and letting people know this won't continue getting tolerated.

Do not tell us what to do. Do not wrongly misinform users what we are doing or try to speak for us. Repeat offenses will get you timed out or banned in the future from our organization. If you have nothing to add to our development process, don't criticize and don't spread disinformation. We only want you here on our Github organization if you are going to contribute code. This is not a forum or a discussion place.

**Pull request closed without merging**
