### PR TITLE
win64 and aarch64 buildbot fixes

### PR DESCRIPTION
**Pull request by flyinghead**

### CODE REVIEW

**Comment by jkaberg** [comment]
@flyinghead where can I find these builds? I couldn't find them for linux (aarch64) @ http://buildbot.libretro.com/nightly/linux/

**Comment by flyinghead** [comment]
Here: http://buildbot.libretro.com/nightly/android/latest/arm64-v8a/

**Comment by jkaberg** [comment]
ah thanks, I guess they wont fly well on linux aarch64 (Lakka)? (target is an Amlogic s905x SoC)

**Comment by flyinghead** [comment]
No, I'm afraid there's no linux aarch64 build for the dolphin core right now

**Comment by jkaberg** [comment]
Ok, I'll add an issue

**Pull request merged**
