### PR TITLE
give rel/abs option to "right stick controls IR"

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by flyinghead — APPROVED** [review]

**Comment by flyinghead** [comment]
@bparker06 while you're at it, can you add code to prevent anything from being bound to the right stick when used for the IR pointer?
In input.cpp, look for `devAnalog + ":Y1"` and  `devAnalog + ":X1"` (lines 577-580 and 625-628 only, lines 525-528 are for gamecube). These lines should not be executed when IR mode is 1 or 2.

**Comment by ghost** [comment]
@flyinghead done

**Comment by flyinghead** [comment]
perfect

**Comment by goedzo** [comment]
Loving it! Thanks :) 👍

**Pull request merged**
