### PR TITLE
turn on multithreading + build fix

### PR DESCRIPTION
**Pull request by jiskattema**

### CODE REVIEW

**Comment by inactive123** [comment]
Hi, is the multithreading stable for this core? Has Linux/Windows/Android been tested?

**Comment by bslenul** [comment]
Insta-crashes for me on Windows 10:
```
retroarch_debug.exe caused an Access Violation at location 0000000000000000 DEP violation at location 0000000000000000.

AddrPC           Params
0000000000000000 0000000000697600 000000000000095E 0000000000000000
00007FFC2223918A 0000000000000000 000000001692FE01 0000000014008CE0  dolphin_libretro.dll!retro_set_video_refresh
00007FFC224AEE36 0000000014008CE0 000000001692FC00 0000000000000001  dolphin_libretro.dll!hid_write
00007FFC220A0018 0000000000000000 0000000008BC5210 0000000000000000  dolphin_libretro.dll!retro_set_video_refresh
00007FFC220A312A 000000001574E940 0000000000000000 0000000000000000  dolphin_libretro.dll!retro_set_video_refresh
00007FFC220A2D29 000000001574E940 0000000000000000 0000000000000000  dolphin_libretro.dll!retro_set_video_refresh
00007FFC90DE1BB2 0000000000000000 0000000000000000 0000000000000000  ucrtbase.dll!_configthreadlocale
00007FFC91C27034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFC932FD241 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart
```

**Comment by jiskattema** [comment]
The bEMUThread is stable for me (ie. ~30 min no crash, several games).
Tested on Linux (fedora 33, and libreelec 9.2)
This is on by default for dolphin, and seems to work fine there, too.

The GFX_BACKEND_MULTITHREADING affects vulkan, which i couldnt test.
This is on by default for dolphin.

**Comment by jiskattema** [comment]
I'm using the 'gl' backend in retroarch, and i have to use set 'Allow cores to switch the video driver' to 'OFF' to prevent an immediate crash. 

I could turn the multithreading into a libretro option, if tthere is interest.
For me, without the multithreading some games are way too slow, even on a NUC8i3.

**Comment by inactive123** [comment]
Turn it into an option in case you can't figure out the crashes on Windows, and default it to off so that Windows doesn't insta-crash moving forward.

**Comment by jiskattema** [comment]
I can now reproduce the crashes, also on linux. Something must have been wrong with my previous build (or retroarch was not using my core, but the default one). 
Please ignore the pull request; thanks for testing it!

**Pull request closed without merging**
